### ISSUE TITLE
[BUG]Sf_Counter input doesn't work with first character typed

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#496] opened 2019-12-05 09:46 UTC
**Describe the bug**
On input field typing the first character will always turn into 0.

**How to reproduce**
1. Click on input field.
2. Start typing different number - 23

**Expected behavior**
It will change to 23 accordingly.

**Actual behavior**
It is 03 instead. The first character is always 0.

**Comment by aniamusial** [comment] 2020-01-22 15:50
@mayashavin closing this one as its no longer valid / cannot reproduce the issue

**Closed by aniamusial** 2020-01-22 15:50 UTC
Labels: bug
