### ISSUE TITLE
[BUG] Failed to compile SfImage

### ISSUE THREAD

**Issue by trileminh94** [DivanteLtd/storefront-ui#1434] opened 2020-09-27 09:17 UTC
**Describe the bug**
Fail to compile error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfImage/SfImage.vue

**How to reproduce**
1. Init project from this repo https://github.com/grantmcconnaughey/cookiecutter-django-vue-graphql-aws
2. Run npm install --save @storefront-ui/vue in frontend directory
3. Run npm install --save-dev css-loader@>1.0.1 scss-loader  sass-loader vue-loader
4. Rebuild project

**Expected behavior**
It should recompile the front end app like normal.

**Actual behavior**
```
ERROR  Failed to compile with 1 errors8:19:52 AM

  error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfImage/SfImage.vue?vue&type=script&lang=js&

 <s> [webpack.Progress] 100%

 Module parse failed: Unexpected token (121:32)
 File was processed with these loaders:
  * ./node_modules/cache-loader/dist/cjs.js
  * ./node_modules/babel-loader/lib/index.js
  * ./node_modules/cache-loader/dist/cjs.js
  * ./node_modules/vue-loader/lib/index.js
 You may need an additional loader to handle the result of these loaders.
 |         deprecationWarning(this.$options.name, "Prop 'src' type should be a string, the object type is deprecated, change the prop type.");
 |         return {
 >           src: this.src.desktop?.url,
 |           srcset: [{
 |             src: this.src.mobile?.url,

  @ ./node_modules/@storefront-ui/vue/src/components/atoms/SfImage/SfImage.vue?vue&type=script&lang=js& 1:0-272 1:288-291 1:293-562 1:293-562
  @ ./node_modules/@storefront-ui/vue/src/components/atoms/SfImage/SfImage.vue
  @ ./node_modules/@storefront-ui/vue/index.js
  @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Components.vue?vue&type=script&lang=js&
  @ ./src/pages/Components.vue?vue&type=script&lang=js&
  @ ./src/pages/Components.vue
  @ ./src/router.js
  @ ./src/main.js
  @ multi (webpack)-dev-server/client?http://0.0.0.0:8000/sockjs-node (webpack)/hot/only-dev-server.js ./src/main.js
```

**Code examples**
empty

**Devices (please complete the following information):**
 - Device: Macbook pro 16inch 2020
 - OS: OSX 10.15.6
 - Browser: chrome

**Additional context**
Vue 2.6.11

**Comment by mayashavin** [comment] 2020-09-29 05:33
Duplicate of #1414 . The bug will be fixed on #1414

**Closed by mayashavin** 2020-09-29 05:33 UTC
Labels: bug
