### ISSUE TITLE
[BUG] SfImage.vue has null propagation that fails on compliation

### ISSUE THREAD

**Issue by ke-real** [DivanteLtd/storefront-ui#1414] opened 2020-09-23 11:14 UTC
**Describe the bug**
Atom component SfImage.vue on lines 117-124 has a null propagation that tends to fail on compilation with vue 2.6.11. This is the only null propagation in the whole project and this whole block is actually marked as deprecated. Can this be removed or replaced with && check?

**How to reproduce**
Compile SF project with "yarn dev"

**Expected behavior**
Complication succeeds

**Actual behavior**
Null propagation fails with syntax error on complication with vue 2.6.11

**Code source**
SfImage.vue line 117
```
src: this.src.desktop?.url,
```

**Comment by mayashavin** [comment] 2020-09-29 05:32
@justyna-13 @ke-real I saw this issue has a PR branch that was merged. Does it mean the issue is resolved?

**Closed** 2020-11-03 13:46 UTC
Labels: bug
