### ISSUE TITLE
[BUG] SfCardHorizontal size and color change from property to select

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1428] opened 2020-09-25 07:47 UTC
**Describe the bug**
SfProductCardHorizontal - size and color are currently SfProperty but on designs they look like SfSelect.

**How to reproduce**
See SfProductCardHorizontal on Storybook layout. Size and color are not select inputs. 

**Expected behavior**
There should be select input for size and color.

Change SfProperty to SfSelect on Storybook stories. 

**Screenshots**
on Figma:
![image](https://user-images.githubusercontent.com/32042425/94240687-eb939280-ff13-11ea-8a66-4f1993fef7ec.png)

current layout:
![image](https://user-images.githubusercontent.com/32042425/94240742-01a15300-ff14-11ea-87de-ee87e6022fd0.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by loongluangkhot** [comment] 2020-09-26 06:09
@AdamPawlinski is this the link to the figma file u took the screenshots from? [Figma link i found from sf-ui contributing guide](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=9282%3A1)

Somehow, the cards I found look differently from the ones u showed. This is what I saw:
<img width="633" alt="Screenshot 2020-09-26 at 2 07 21 PM" src="https://user-images.githubusercontent.com/10969759/94331769-cda45b80-0001-11eb-90df-bf55d41c48f9.png">

**Comment by loongluangkhot** [comment] 2020-09-26 16:39
@mayashavin could u assign this one to me? Thx loads!!!!

**Comment by AdamPawlinski** [comment] 2020-09-26 17:58
@loongluangkhot Yes you are right this designs are outdated so please take a look on https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=4472%3A11536. I assigned you this issue. Thanks for your participation :)

**Comment by loongluangkhot** [comment] 2020-10-01 14:56
@AdamPawlinski I have submitted a pull request: https://github.com/DivanteLtd/storefront-ui/pull/1448

I'm not so sure how to assign reviewers to the pull request?

Also, while working on this issue, i realized that there are a few enhancements needed on SfSelect:

1. It currently doesn't take in a prop for default selected option. I think this will be a useful feature.
2. There is a bug in the selection. You can reproduce this in the current [official storybook](https://storybook.storefrontui.io/?path=/story/molecules-select--common) with the steps shown in the GIF below:

![SfSelect_bug](https://user-images.githubusercontent.com/10969759/94825910-4b6cca80-0439-11eb-8090-5da71bfe06f4.gif)

**Comment by AdamPawlinski** [comment] 2020-10-02 11:12
Thanks @loongluangkhot, really nice work :+1: . Regarding your questions, you can propose new issue for the default selected option. If you have any ideas regarding refactoring placeholder I can assign you this task.
Does this selection bug appear on Mac OS? if so, we could have missed that. So it could be nice if you also add new issue that.
#1321 is the old issue and since that SfSelect was refactored to be more native. We have also SfComponentSelect which is older version of SFSelect, but strongly customized.

**Comment by loongluangkhot** [comment] 2020-10-02 13:35
Is refactoring placeholder part of #1321 ? From what I read, it seems that #1321 specifically mentioned two things: (1) semantics and (2) scrollbar, and they seemed to both be done. Is there anything I'm missing?

On a different note, I'll create two new tickets as you suggested: (1) New feature: default selected option, and (2) Bug: selecting on MacOS malfunctions (I think I should check on Windows. My gut feeling is that this bug should appear too since I'm using Chrome)

**Comment by loongluangkhot** [comment] 2020-10-02 13:41
Hmm interestingly, the bug only exists on MacOS. It functions perfectly on Chrome on Windows!

**Comment by loongluangkhot** [comment] 2020-10-02 14:13
Opened the tickets: #1455 & #1456

**Closed** 2020-11-02 09:28 UTC
Labels: bug, good first issue, hacktoberfest
