### ISSUE TITLE
[BUG]SfSteps 

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/storefront-ui#971] opened 2020-04-01 08:29 UTC
**Describe the bug**
After performing v-if on one of the steps, which is initially true and changes to false, this step does not disappear from view and still occurs.
It is possible that it is copied to 'data' so maybe it is not refreshed later.

**How to reproduce**
1. Give about 3 steps
2. On the first one give v-if where the flag points to true
3. Change the flag
4. Step remains visible

**Expected**
A request for verification and a fix for this in 0.6.5 fix if possible

**Actual behavior**
 It breaks the workflow in checkout

**Comment by cnviradiya** [comment] 2020-08-04 11:49
@akrajna Will you please describe more this issue?
I just check with the version `0.7.18` & not able to reproduce the issue. Might be fixed in the latest version.

![screencast-localhost_3000-2020 08 04-17_17_16](https://user-images.githubusercontent.com/9442993/89290502-95724380-d676-11ea-995e-cb4177715e48.gif)

**Comment by justyna-13** [comment] 2020-09-24 07:40
fixed in the previous version

**Closed by justyna-13** 2020-09-24 07:40 UTC
Labels: bug
